- name: Install dependencies
  hosts: all
  become: true
  gather_facts: False
  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: ['python3-pip', 'virtualenv', 'python3-setuptools']
    - name: Install python stuff required
      pip:
        executable: pip3
        name: [jsondiff, passlib, docker]

- name: Configure Docker Swarm Master
  hosts: master
  become: true
  gather_facts: False

  tasks:
    - name: Initialize Docker Swarm
      docker_swarm:
        state: present
        advertise_addr: "{{ ansible_host }}"
        listen_addr: "0.0.0.0"
      register: master_output

- name: Configure Docker Swarm Worker
  hosts: worker
  become: true
  gather_facts: False

  tasks:
    - name: Join Docker Swarm
      docker_swarm:
        state: join
        join_token: "{{ hostvars[groups['master'][0]].master_output.swarm_facts.JoinTokens.Worker }}"
        advertise_addr: "{{ ansible_host }}"
        remote_addrs: "{{ hostvars[groups['master'][0]].inventory_hostname }}"