version: "3.3"

services:
  app:
    image: app
    deploy:
      replicas: 3

  nginx:
    image: nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app